// Code generated by MockGen. DO NOT EDIT.
// Source: stock_spotter/internal/mailer (interfaces: Mailer)
//
// Generated by this command:
//
//	mockgen -destination=./mailer_mock.go -package=mailer . Mailer
//

// Package mailer is a generated GoMock package.
package mailer

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendMail mocks base method.
func (m *MockMailer) SendMail(ctx context.Context, cfg Config) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMail", ctx, cfg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMail indicates an expected call of SendMail.
func (mr *MockMailerMockRecorder) SendMail(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMail", reflect.TypeOf((*MockMailer)(nil).SendMail), ctx, cfg)
}
