// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./auth_mock.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"
	time "time"
	user "whatsapp/internal/user"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthStore is a mock of AuthStore interface.
type MockAuthStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuthStoreMockRecorder
	isgomock struct{}
}

// MockAuthStoreMockRecorder is the mock recorder for MockAuthStore.
type MockAuthStoreMockRecorder struct {
	mock *MockAuthStore
}

// NewMockAuthStore creates a new mock instance.
func NewMockAuthStore(ctrl *gomock.Controller) *MockAuthStore {
	mock := &MockAuthStore{ctrl: ctrl}
	mock.recorder = &MockAuthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthStore) EXPECT() *MockAuthStoreMockRecorder {
	return m.recorder
}

// ActivateUserAccount mocks base method.
func (m *MockAuthStore) ActivateUserAccount(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUserAccount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUserAccount indicates an expected call of ActivateUserAccount.
func (mr *MockAuthStoreMockRecorder) ActivateUserAccount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUserAccount", reflect.TypeOf((*MockAuthStore)(nil).ActivateUserAccount), ctx, userID)
}

// CheckUserEmailExists mocks base method.
func (m *MockAuthStore) CheckUserEmailExists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserEmailExists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserEmailExists indicates an expected call of CheckUserEmailExists.
func (mr *MockAuthStoreMockRecorder) CheckUserEmailExists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserEmailExists", reflect.TypeOf((*MockAuthStore)(nil).CheckUserEmailExists), ctx, email)
}

// CreateGoogleUser mocks base method.
func (m *MockAuthStore) CreateGoogleUser(ctx context.Context, arg1 *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGoogleUser", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGoogleUser indicates an expected call of CreateGoogleUser.
func (mr *MockAuthStoreMockRecorder) CreateGoogleUser(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGoogleUser", reflect.TypeOf((*MockAuthStore)(nil).CreateGoogleUser), ctx, arg1)
}

// CreateSession mocks base method.
func (m *MockAuthStore) CreateSession(ctx context.Context, userID uuid.UUID, token, ip, userAgent string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, userID, token, ip, userAgent, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockAuthStoreMockRecorder) CreateSession(ctx, userID, token, ip, userAgent, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockAuthStore)(nil).CreateSession), ctx, userID, token, ip, userAgent, expiresAt)
}

// CreateUser mocks base method.
func (m *MockAuthStore) CreateUser(ctx context.Context, arg1 *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthStoreMockRecorder) CreateUser(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthStore)(nil).CreateUser), ctx, arg1)
}

// DeleteAllUserSessions mocks base method.
func (m *MockAuthStore) DeleteAllUserSessions(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllUserSessions indicates an expected call of DeleteAllUserSessions.
func (mr *MockAuthStoreMockRecorder) DeleteAllUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUserSessions", reflect.TypeOf((*MockAuthStore)(nil).DeleteAllUserSessions), ctx, userID)
}

// DeleteSession mocks base method.
func (m *MockAuthStore) DeleteSession(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockAuthStoreMockRecorder) DeleteSession(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockAuthStore)(nil).DeleteSession), ctx, token)
}

// FindByEmail mocks base method.
func (m *MockAuthStore) FindByEmail(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockAuthStoreMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockAuthStore)(nil).FindByEmail), ctx, email)
}

// FindUserByActivationToken mocks base method.
func (m *MockAuthStore) FindUserByActivationToken(ctx context.Context, token string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByActivationToken", ctx, token)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByActivationToken indicates an expected call of FindUserByActivationToken.
func (mr *MockAuthStoreMockRecorder) FindUserByActivationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByActivationToken", reflect.TypeOf((*MockAuthStore)(nil).FindUserByActivationToken), ctx, token)
}

// FindUserByGoogleID mocks base method.
func (m *MockAuthStore) FindUserByGoogleID(ctx context.Context, googleID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByGoogleID", ctx, googleID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByGoogleID indicates an expected call of FindUserByGoogleID.
func (mr *MockAuthStoreMockRecorder) FindUserByGoogleID(ctx, googleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByGoogleID", reflect.TypeOf((*MockAuthStore)(nil).FindUserByGoogleID), ctx, googleID)
}

// FindUserByResetToken mocks base method.
func (m *MockAuthStore) FindUserByResetToken(ctx context.Context, token string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByResetToken", ctx, token)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByResetToken indicates an expected call of FindUserByResetToken.
func (mr *MockAuthStoreMockRecorder) FindUserByResetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByResetToken", reflect.TypeOf((*MockAuthStore)(nil).FindUserByResetToken), ctx, token)
}

// FindUserBySession mocks base method.
func (m *MockAuthStore) FindUserBySession(ctx context.Context, token string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserBySession", ctx, token)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserBySession indicates an expected call of FindUserBySession.
func (mr *MockAuthStoreMockRecorder) FindUserBySession(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserBySession", reflect.TypeOf((*MockAuthStore)(nil).FindUserBySession), ctx, token)
}

// GetLoginAttempts mocks base method.
func (m *MockAuthStore) GetLoginAttempts(ctx context.Context, email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginAttempts", ctx, email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginAttempts indicates an expected call of GetLoginAttempts.
func (mr *MockAuthStoreMockRecorder) GetLoginAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginAttempts", reflect.TypeOf((*MockAuthStore)(nil).GetLoginAttempts), ctx, email)
}

// IncrementLoginAttempts mocks base method.
func (m *MockAuthStore) IncrementLoginAttempts(ctx context.Context, email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementLoginAttempts", ctx, email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementLoginAttempts indicates an expected call of IncrementLoginAttempts.
func (mr *MockAuthStoreMockRecorder) IncrementLoginAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementLoginAttempts", reflect.TypeOf((*MockAuthStore)(nil).IncrementLoginAttempts), ctx, email)
}

// ResetLoginAttempts mocks base method.
func (m *MockAuthStore) ResetLoginAttempts(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetLoginAttempts", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetLoginAttempts indicates an expected call of ResetLoginAttempts.
func (mr *MockAuthStoreMockRecorder) ResetLoginAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetLoginAttempts", reflect.TypeOf((*MockAuthStore)(nil).ResetLoginAttempts), ctx, email)
}

// SaveResetPasswordToken mocks base method.
func (m *MockAuthStore) SaveResetPasswordToken(ctx context.Context, userID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResetPasswordToken", ctx, userID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResetPasswordToken indicates an expected call of SaveResetPasswordToken.
func (mr *MockAuthStoreMockRecorder) SaveResetPasswordToken(ctx, userID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResetPasswordToken", reflect.TypeOf((*MockAuthStore)(nil).SaveResetPasswordToken), ctx, userID, token)
}

// UpdateGoogleUserInfo mocks base method.
func (m *MockAuthStore) UpdateGoogleUserInfo(ctx context.Context, userID uuid.UUID, firstName, lastName, profilePicture string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGoogleUserInfo", ctx, userID, firstName, lastName, profilePicture)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGoogleUserInfo indicates an expected call of UpdateGoogleUserInfo.
func (mr *MockAuthStoreMockRecorder) UpdateGoogleUserInfo(ctx, userID, firstName, lastName, profilePicture any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGoogleUserInfo", reflect.TypeOf((*MockAuthStore)(nil).UpdateGoogleUserInfo), ctx, userID, firstName, lastName, profilePicture)
}

// UpdateLastLogin mocks base method.
func (m *MockAuthStore) UpdateLastLogin(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockAuthStoreMockRecorder) UpdateLastLogin(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockAuthStore)(nil).UpdateLastLogin), ctx, userID)
}

// UpdateUserPassword mocks base method.
func (m *MockAuthStore) UpdateUserPassword(ctx context.Context, userID uuid.UUID, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, userID, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockAuthStoreMockRecorder) UpdateUserPassword(ctx, userID, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockAuthStore)(nil).UpdateUserPassword), ctx, userID, hashedPassword)
}
